pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - docker build --pull --no-cache -t sickrage-dev .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -d --user=root sickrage-dev)
      - timeout -t 12 -- docker logs -f $$CON_NAME | cat &
      - sleep 10
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -L --retry-max-time 30 --max-time 5 --retry 10 --retry-delay 5 --retry-connrefused $IP:8081 > /dev/null
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME

  publish:
    image: docker
    when:
      event: [push, tag, deployment]
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - apk add --no-cache openssl
         # Grab just the version, not the hash. Used for tagging
       - echo $DOCKER_USER
       - docker tag sickrage-dev adamant/sickrage:latest
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/sickrage
       - docker rmi sickrage-dev adamant/sickrage
       - echo "CONGRATS! SUCCESSFULLY BUILT SICKRAGE!"
