pipeline:
  identify:
    image: alpine
    commands:
      - apk add --no-cache curl jq
      - set -o pipefail
      - curl -fL https://api.github.com/repos/Sickrage/Sickrage/tags
          | jq '.[0]'
          | tee /dev/stderr
          | jq -r .name > .sickrage_tag

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: sickrage-dev
    build_args:
      - 'SICKRAGE_VER=%file: .sickrage_tag'

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -d -e SUID=0 sickrage-dev)
      - timeout -t 12 -- docker logs -f $$CON_NAME | cat &
      - sleep 10
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -L --retry-max-time 30 --max-time 5 --retry 10 --retry-delay 5 --retry-connrefused $IP:8081 > /dev/null
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: sickrage-dev
    repo: spritsail/sickrage
    tags:
      - 'latest'
      - '%fileauto: .sickrage_tag'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
