pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - docker build -t sickrage-dev . 

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run --rm -d -p 8081:8081 --user=root sickrage-dev) # Need root for config
      - sleep 15  # Wait for SickRage to start!
      - docker logs $$CON_NAME
      - curl -sSL --max-time 5 --retry 5 --retry-delay 5 $(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME):8081  > /dev/null 
      - docker kill $$CON_NAME # Not really needed, but keeps things quick

  publish:
    image: docker
    when:
      event: [push, tag, deployment]
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - apk add --no-cache openssl
         # Grab just the version, not the hash. Used for tagging
       - echo $DOCKER_USER
       - docker tag sickrage-dev adamant/sickrage:latest
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/sickrage
       - docker rmi sickrage-dev adamant/sickrage
       - echo "CONGRATS! SUCCESSFULLY BUILT SICKRAGE!"
